version: 2.1

orbs:
  maven: circleci/maven@1.0.3
  browser-tools: circleci/browser-tools@1.1.0

jobs:
  build:
    docker:
      - image: cimg/openjdk:15.0-browsers
    steps:
      - browser-tools/install-browser-tools

workflows:
  build-then-test:
    jobs:
      - build
      - maven/test:
          requires:
            - build
